# Generated by Django 4.2.8 on 2024-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('last_name', 'name'),
            },
        ),
    ]