# Generated by Django 4.2.8 on 2024-01-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
    ]
